name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.18
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: true

    - name: Load Dependencies
      run: make vendor
      
    - name: Build
      run: make build
